val_scores [ 0.02126826 -0.02354689  0.06698611]
val_scores_mean 0.0215691586529
test_score:  0.5398083886
mape_socre:  3.20884563932
test_score:  0.563738948854
mape_socre:  3.48072026566
Traceback (most recent call last):
  File "train_gg_atw.py", line 77, in <module>
    val_scores = cross_val_score(rfr, train_data, train_target_data, cv=3, n_jobs=3)
NameError: name 'rfr' is not defined
val_scores [-0.04235419 -0.06636311  0.03194086]
val_scores_mean -0.025592146992
Traceback (most recent call last):
  File "train_gg_atw.py", line 109, in <module>
    test_score = clf.score(test_data, test_target_data)
  File "/root/.pyenv/versions/anaconda-4.0.0/lib/python2.7/site-packages/sklearn/base.py", line 347, in score
    return r2_score(y, self.predict(X), sample_weight=sample_weight,
  File "/root/.pyenv/versions/anaconda-4.0.0/lib/python2.7/site-packages/sklearn/ensemble/forest.py", line 649, in predict
    X = self._validate_X_predict(X)
  File "/root/.pyenv/versions/anaconda-4.0.0/lib/python2.7/site-packages/sklearn/ensemble/forest.py", line 316, in _validate_X_predict
    raise NotFittedError("Estimator not fitted, "
sklearn.utils.validation.NotFittedError: Estimator not fitted, call `fit` before exploiting the model.
Traceback (most recent call last):
  File "train_gg_atw.py", line 72, in <module>
    clf = rfr.fit(train_data, train_target_data)
NameError: name 'rfr' is not defined
